linters:
  enable-all: true
  disable:
    - exportloopref
    - gofumpt
    - wsl
    - wrapcheck
    - varnamelen
    - testpackage
    - ireturn
    - nlreturn
    - gochecknoglobals
    - exhaustruct
    - godot
    - depguard
    - err113
    - gci
    - forbidigo
    - gocognit
    - gocyclo
    - cyclop
    - maintidx
linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  staticcheck:
    checks:
      - '-SA4004'
  mnd:
    ignored-files:
      - pkg/parser/split.go
  revive:
    rules:
      - name: dot-imports
        disabled: true
  gofmt:
    simplify: false
  stylecheck:
    checks:
      - ST1000 # Incorrect or missing package comment.
      - ST1003 # Poorly chosen identifier.
      - ST1005 # Incorrectly formatted error string.
      - ST1006 # Poorly chosen receiver name.
      - ST1008 # A function's error value should be its last return value.
      - ST1011 # Poorly chosen name for variable of type 'time.Duration'.
      - ST1012 # Poorly chosen name for error variable.
      - ST1013 # Should use constants for HTTP error codes, not magic numbers.
      - ST1015 # A switch's default case should be the first or last case.
      - ST1016 # Use consistent method receiver names.
      - ST1017 # Don't use Yoda conditions.
      - ST1018 # Avoid zero-width and control characters in string literals.
      - ST1019 # Importing the same package multiple times.
      - ST1020 # The documentation of an exported function should start with the function's name.
      - ST1021 # The documentation of an exported type should start with type's name.
      - ST1022 # The documentation of an exported variable or constant should start with variable's name.
      - ST1023 # Redundant type in variable declaration.
