package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/AhmedMoalla/quadlet-lint/pkg/model"
)

func generateSourceFiles(data quadletSourceFileData) error {
	workingDir, err := os.Getwd()
	if err != nil {
		panic(err)
	}

	outputDir := filepath.Join(workingDir, "generated")
	err = os.Mkdir(outputDir, 0777)
	if err != nil && !os.IsExist(err) {
		return err
	}

	err = generateFile(outputDir, data.fieldsByGroup, "groups.go", groupsFile)
	if err != nil {
		return err
	}

	for group := range data.fieldsByGroup {
		groupLower := strings.ToLower(group)
		path := fmt.Sprintf("%s/%s.go", groupLower, groupLower)
		err = generateFile(outputDir, data.fieldsByGroup, path, groupFile(group))
		if err != nil {
			return err
		}
	}

	return nil
}

type FileGenerator = func(*bytes.Buffer, map[string][]string)

func generateFile(outputDir string, fieldsByGroup map[string][]string, filename string, generateFileContent FileGenerator) error {
	dir, filename := filepath.Split(filename)
	fileDir := filepath.Join(outputDir, dir)
	if len(dir) > 0 {
		err := os.MkdirAll(fileDir, 0777)
		if err != nil && !os.IsExist(err) {
			return err
		}
	}

	path := filepath.Join(fileDir, filename)
	file, err := os.Create(path)
	if err != nil {
		return err
	}

	sb := bytes.Buffer{}
	sb.WriteString(fmt.Sprintf("// Code generated by \"quadlet-model-gen\"; PodmanVersion=%s; DO NOT EDIT.\n", *podmanVersion))
	generateFileContent(&sb, fieldsByGroup)

	formatted, err := format.Source(sb.Bytes())
	if err != nil {
		return err
	}

	_, err = file.Write(formatted)
	if err != nil {
		return err
	}

	return nil
}

func groupsFile(b *bytes.Buffer, fieldsByGroup map[string][]string) {
	b.WriteString("package model\n\n")
	b.WriteString("import (\n")
	for group := range fieldsByGroup {
		b.WriteString(fmt.Sprintf("\t\"%s/%s\"\n", baseModelPackageName, strings.ToLower(group)))
	}
	b.WriteString("\tM \"github.com/AhmedMoalla/quadlet-lint/pkg/model\"\n")
	b.WriteString(")\n\n")

	b.WriteString("type Groups struct {\n")
	for group := range fieldsByGroup {
		b.WriteString(fmt.Sprintf("\t%s %s.G%s\n", group, strings.ToLower(group), group))
	}
	b.WriteString("}\n\n")

	b.WriteString("var Fields =  map[string]map[string]M.Field{\n")
	for group, fields := range fieldsByGroup {
		b.WriteString(fmt.Sprintf("\t\"%s\": {\n", group))
		for _, field := range fields {
			b.WriteString(fmt.Sprintf("\t\t\"%s\": %s.%s,\n", field, strings.ToLower(group), field))
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
}

func groupFile(group string) FileGenerator {
	return func(b *bytes.Buffer, fieldsByGroup map[string][]string) {
		b.WriteString(fmt.Sprintf("package %s\n\n", strings.ToLower(group)))
		if len(fieldsByGroup[group]) > 0 {
			b.WriteString("import (\n")
			b.WriteString("\tM \"github.com/AhmedMoalla/quadlet-lint/pkg/model\"\n")
			b.WriteString("\tV \"github.com/AhmedMoalla/quadlet-lint/pkg/validator\"\n")
			b.WriteString(")\n\n")
		}

		b.WriteString(fmt.Sprintf("type G%s struct {\n", group))
		for _, field := range fieldsByGroup[group] {
			b.WriteString(fmt.Sprintf("\t%s []V.Rule\n", field))
		}
		b.WriteString("}\n\n")

		b.WriteString("var (\n")
		for _, fieldName := range fieldsByGroup[group] {
			field := model.Field{
				Group: group,
				Key:   fieldName,
			}

			if meta, ok := model.FieldsMetadata[group][fieldName]; ok {
				field.Multiple = meta.Multiple
			}

			fieldStr := strings.Replace(fmt.Sprintf("%#v", field), "model.", "M.", 1)
			b.WriteString(fmt.Sprintf("\t%s = %s\n", fieldName, fieldStr))
		}
		b.WriteString(")\n")
	}
}
