package main

import (
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
)

const (
	podmanVersionFlag    = "podman-version"
	podmanVersionEnvKey  = "PODMAN_VERSION"
	quadletFileLocation  = "https://raw.githubusercontent.com/containers/podman/refs/tags/%s/pkg/systemd/quadlet/quadlet.go"
	baseModelPackageName = "github.com/AhmedMoalla/quadlet-lint/pkg/generated/model"
)

var (
	podmanVersion = flag.String(podmanVersionFlag, "", "Podman's tag used to download the source file for code generation")
)

// TODO: gofmt generated files
// Download the quadlet.go file from given podman tag version
//
//	Use: https://raw.githubusercontent.com/containers/podman/refs/tags/v5.3.1/pkg/systemd/quadlet/quadlet.go
//
// Parse the group variables to extract group names
// Create a groups.go file and create the Groups struct in it
// For each group:
// - Generate a package with a single file under the validator/generated package
// - In the file:
//   - Create a struct with the group's name and add a field of type []V.Rule for each supported key (Supported keys are in the maps, e.g.: supportedContainerKeys for Container group for example)
//   - Create a variable of type P.Field for each supported field encountered
//
// - In the groups.go file:
//   - Add a field for the group pointing to the structure created previously
//   - Add all the fields in the Fields map
func main() {
	flag.Parse()

	podmanVersion := getPodmanVersion(*podmanVersion)
	quadletSourceFile, err := downloadQuadletSourceFileFromGithub(podmanVersion)
	if err != nil {
		exit(fmt.Errorf("could not download quadlet quadletSourceFile: %s", err))
	}
	defer os.Remove(quadletSourceFile.Name())

	data, err := parseQuadletSourceFile(quadletSourceFile)
	if err != nil {
		exit(fmt.Errorf("could not parse quadlet source file: %s", err))
	}

	err = generateSourceFiles(data)
	if err != nil {
		exit(fmt.Errorf("could not generate source files: %s", err))
	}
}

func generateSourceFiles(data quadletSourceFileData) error {
	workingDir, err := os.Getwd()
	if err != nil {
		panic(err)
	}

	modelDir := filepath.Join(workingDir, "model")
	err = os.Mkdir(modelDir, 0777)
	if err != nil && !os.IsExist(err) {
		return err
	}

	groupsFilePath := filepath.Join(modelDir, "groups.go")
	groupsFile, err := os.Create(groupsFilePath)
	if err != nil {
		return err
	}

	err = generateGroupsFileContent(groupsFile, data.fieldsByGroup)
	if err != nil {
		return err
	}

	return nil
}

func generateGroupsFileContent(groupsFile *os.File, fieldsByGroup map[string][]string) error {
	sb := strings.Builder{}
	sb.WriteString("// Code generated by \"quadlet-model-gen\"; DO NOT EDIT.\n")
	sb.WriteString("package model\n\n")
	sb.WriteString("import (\n")
	for group := range fieldsByGroup {
		sb.WriteString(fmt.Sprintf("\t\"%s/%s\"\n", baseModelPackageName, strings.ToLower(group)))
	}
	sb.WriteString("\tP \"github.com/AhmedMoalla/quadlet-lint/pkg/parser\"\n")
	sb.WriteString(")\n\n")

	sb.WriteString("type Groups struct {\n")
	for group := range fieldsByGroup {
		sb.WriteString(fmt.Sprintf("\t%s %s.%s\n", group, strings.ToLower(group), group))
	}
	sb.WriteString("}\n\n")

	sb.WriteString("var Fields = map[string]P.Field{\n")
	for group, fields := range fieldsByGroup {
		sb.WriteString(fmt.Sprintf("\t// %s group fields\n", group))
		for _, field := range fields {
			sb.WriteString(fmt.Sprintf("\t\"%s\": %s.%s,\n", field, strings.ToLower(group), field))
		}
		sb.WriteString("\n")
	}
	sb.WriteString("}\n")

	_, err := groupsFile.WriteString(sb.String())
	if err != nil {
		return err
	}

	return nil
}

func exit(err error) {
	_, err = fmt.Fprintf(os.Stderr, "%s\n", err.Error())
	if err != nil {
		panic(err)
	}
	os.Stderr.Sync()
	os.Exit(1)
}

func getPodmanVersion(version string) string {
	if version == "" {
		if version, ok := os.LookupEnv(podmanVersionEnvKey); ok {
			return version
		}
	}

	return version
}

func downloadQuadletSourceFileFromGithub(version string) (*os.File, error) {
	if version == "" {
		return nil, fmt.Errorf("podman version was not provided. "+
			"Use -%s flag or %s environment variable", podmanVersionFlag, podmanVersionEnvKey)
	}

	url := fmt.Sprintf(quadletFileLocation, version)
	client := http.Client{}
	response, err := client.Get(url)
	if err != nil {
		return nil, fmt.Errorf("failed to download from '%s': %v", url, err)
	}
	defer response.Body.Close()

	if response.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("unexpected status '%s' when downloading from '%s'", response.Status, url)
	}

	file, err := os.CreateTemp("", "quadlet-*.go")
	if err != nil {
		return nil, fmt.Errorf("failed to create temporary file to copy the content of quadlet file: %v", err)
	}
	defer file.Close()

	_, err = io.Copy(file, response.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to copy file contents: %v", err)
	}

	return file, nil
}
