name: Build

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

env:
  GO_VERSION: '1.23.4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '$GO_VERSION'

      - name: Build quadlet-lint
        run: make build

      - name: Run tests
        run: make test
  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '$GO_VERSION'

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
