name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Build quadlet-lint
        run: make build

      - name: Run tests
        run: make test

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63.4
